custom_tags:
- {name: event, description: Event trigger area}
- {name: destination, description: General destination point}
- {name: landmark, description: Landmark for guidance}
- {name: audio_info, description: Audio guide trigger}
route:
- name: route_1
  waypoints: [meeting_room_a, conference_room, corridor_a, model_exhibit]
- name: route_2
  waypoints: [elevator_hall, corridor_a, conference_room]
map:
- {node_name: /map_server, map_file: turtlebot3.yaml}
poi:
- description: エレベーターホール
  name: elevator_hall
  pose: {x: -2, y: -0.5, yaw: 0}
  radius: 0.5
  tags: [goal, initial_pose]
- description: 会議室A
  name: meeting_room_a
  pose: {x: -0.5, y: -0.5, yaw: 0}
  radius: 0.5
  tags: [goal]
- description: 大会議室
  name: conference_room
  pose: {x: 0.5, y: -0.5, yaw: 1.57}
  radius: 0.5
  tags: [goal]
- description: 廊下
  name: corridor_a
  pose: {x: 0.5, y: 0.5, yaw: -3.14}
  radius: 0.5
  tags: [goal]
- description: 模型展示
  name: model_exhibit
  pose: {x: -0.5, y: 0.5, yaw: -1.57}
  radius: 0.5
  tags: [goal, audio_info]
